name: Update GitHub README Stats
on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 1/2 * *
  push:
    branches:
      - master
    paths:
      - .github/workflows/update-readme-stats.yml

concurrency:
  # github.event.pull_request.number || github.ref: pull request number or branch name if not a pull request
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CHECK_PERMISSIONS: 0

permissions: {}

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    name: Generate stats cards
    permissions:
      contents: write
    steps:
      - id: check-permissions
        name: Check action permissions
        uses: GitHubSecurityLab/actions-permissions/monitor@bf82d13b9b10051d224345ab9184f5ede0a94289 # v1.0.2-beta9
        if: env.CHECK_PERMISSIONS == '1'
      - id: checkout-repo
        name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: true
      - id: generate-stats-default
        name: Generate default stats
        uses: stats-organization/github-readme-stats-action@b4d2ef3b8051484b318d455163153b23a2b35fa2 # v1.1.0
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&count_private=true&include_all_commits=true&number_format=long&hide_title=true&hide_rank=true&show=discussions_started,prs_merged&hide_border=true&theme=default
          path: img/stats-default.svg
          token: ${{ secrets.GITHUB_TOKEN }}
      - id: generate-stats-dark
        name: Generate dark stats
        uses: stats-organization/github-readme-stats-action@b4d2ef3b8051484b318d455163153b23a2b35fa2 # v1.1.0
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&count_private=true&include_all_commits=true&number_format=long&hide_title=true&hide_rank=true&show=discussions_started,prs_merged&hide_border=true&theme=dark
          path: img/stats-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}
      - id: generate-langs-default
        name: Generate default langs
        uses: stats-organization/github-readme-stats-action@b4d2ef3b8051484b318d455163153b23a2b35fa2 # v1.1.0
        with:
          options: username=${{ github.repository_owner }}&layout=donut&langs_count=20&hide_border=true&disable_animations=true&theme=default
          path: img/langs-default.svg
          card: top-langs
          token: ${{ secrets.GITHUB_TOKEN }}
      - id: generate-langs-dark
        name: Generate dark langs
        uses: stats-organization/github-readme-stats-action@b4d2ef3b8051484b318d455163153b23a2b35fa2 # v1.1.0
        with:
          options: username=${{ github.repository_owner }}&layout=donut&langs_count=20&hide_border=true&disable_animations=true&theme=dark
          path: img/langs-dark.svg
          card: top-langs
          token: ${{ secrets.GITHUB_TOKEN }}
      - id: commit-cards
        name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add img/langs-*.svg
          git add img/stats-*.svg
          git commit -m "Update README cards" || exit 0
          git push
